option(SAKURA_DISTRIBUTION "Build a production distribution client" OFF)
set(SAKURA_RELEASE_VERSION "0.1.2" CACHE STRING "Client release version")
set(SAKURA_CA_FILE "" CACHE FILEPATH "Optional public CA certificate bundled in distribution")
if(SAKURA_CA_FILE)
    file(READ "${SAKURA_CA_FILE}" SAKURA_CA_PEM)
    if(NOT SAKURA_CA_PEM MATCHES "-----BEGIN CERTIFICATE-----" OR SAKURA_CA_PEM MATCHES "PRIVATE KEY")
        message(FATAL_ERROR "CA file must contain public PEM certificates only")
    endif()
endif()
set(SAKURA_GITHUB_REPOSITORY "shimamuraDS/SakuraChat" CACHE STRING "Public GitHub releases repository")
if(NOT SAKURA_GITHUB_REPOSITORY MATCHES "^[A-Za-z0-9_-]+/[A-Za-z0-9_.-]+$")
    message(FATAL_ERROR "GitHub repository must be owner/repository")
endif()
foreach(field GATEWAY PUBLISHER)
    set(SAKURA_${field} "" CACHE STRING "Distribution ${field}")
endforeach()
if(NOT SAKURA_RELEASE_VERSION MATCHES "^[0-9]+[.][0-9]+[.][0-9]+$")
    message(FATAL_ERROR "Release version must be numeric major.minor.patch")
endif()
if(SAKURA_DISTRIBUTION)
    if(NOT WIN32 OR NOT CMAKE_BUILD_TYPE STREQUAL "Release")
        message(FATAL_ERROR "Distribution requires a Windows Release build")
    endif()
    foreach(field GATEWAY)
        if(NOT SAKURA_${field} MATCHES "^https://[A-Za-z0-9.-]+(:[0-9]+)?(/[-A-Za-z0-9._~/]*)?$" OR SAKURA_${field} MATCHES "localhost|127[.]0[.]0[.]1|[.]invalid|[.]example")
            message(FATAL_ERROR "Missing or unsafe production ${field}")
        endif()
    endforeach()
    if(NOT SAKURA_PUBLISHER MATCHES "^[A-Za-z0-9 ._-]+$")
        message(FATAL_ERROR "Set a stable publisher identifier (ASCII letters, digits, spaces, ._-)")
    endif()
endif()
configure_file("${CMAKE_CURRENT_LIST_DIR}/releaseconfig.h.in" "${CMAKE_CURRENT_BINARY_DIR}/generated/releaseconfig.h" @ONLY)
if(WIN32)
    string(REPLACE "." "," SAKURA_VERSION_TUPLE "${SAKURA_RELEASE_VERSION}")
    configure_file("${CMAKE_CURRENT_LIST_DIR}/../release/version.rc.in" "${CMAKE_CURRENT_BINARY_DIR}/generated/version.rc" @ONLY)
endif()
